#!/usr/bin/env python3
# gendex.py
# @spiralbend 2025-07-29

import os
import stat
import argparse
import datetime
from pathlib import Path

# --- LS_COLORS support ----------------------------------------------------
# ANSI color to CSS color mapping for foreground
FG = {
    30: "black",
    31: "red",
    32: "green",
    33: "yellow",
    34: "dodgerblue",
    35: "magenta",
    36: "cyan",
    37: "white",
}
# ANSI color to CSS background mapping (40–47)
BG = {code + 10: color for code, color in FG.items()}
skipped = 0


def parse_ls_colors():
    """Parse LS_COLORS env var and return dict of {key: 'css:prop;…'}"""
    raw = os.getenv("LS_COLORS", "")
    cmap = {}
    for part in raw.split(":"):
        if "=" not in part:
            continue
        key, val = part.split("=", 1)
        codes = [int(x) for x in val.split(";") if x.isdigit()]
        styles = []
        for c in codes:
            if c == 1:
                styles.append("font-weight:bold")
            elif c == 4:
                styles.append("text-decoration:underline")
            elif c in FG:
                styles.append(f"color:{FG[c]}")
            elif c in BG:
                styles.append(f"background-color:{BG[c]}")
        if styles:
            cmap[key] = ";".join(styles)
    return cmap


LS_COLOR_MAP = parse_ls_colors()


def get_color_style(st_mode, full_path):
    """
    Determine CSS style from LS_COLOR_MAP based on file type or extension.
    """
    if stat.S_ISDIR(st_mode):
        key = "di"
    elif stat.S_ISLNK(st_mode):
        key = "ln"
    elif stat.S_ISFIFO(st_mode):
        key = "pi"
    elif stat.S_ISSOCK(st_mode):
        key = "so"
    elif stat.S_ISBLK(st_mode):
        key = "bd"
    elif stat.S_ISCHR(st_mode):
        key = "cd"
    else:
        key = "ex" if os.access(full_path, os.X_OK) else "fi"
    if key in LS_COLOR_MAP:
        return LS_COLOR_MAP[key]
    name = full_path.lower()
    for pat, style in sorted(LS_COLOR_MAP.items(), key=lambda x: -len(x[0])):
        if pat.startswith("*.") and name.endswith(pat[1:].lower()):
            return style
    return ""


# ---------------------------------------------------------------------------

TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/x-icon" href="/favicon.ico?v=2">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Index of /{path}</title>
    <style>
        html,body,pre,span,a {{
            background-color: black !important;
            font-size: 12pt;
        }}        
        @media (max-width: 500px) {{
            html,body,pre,span,a {{ 
                font-size: 8pt;
            }}
        }}
        body {{
            margin: 0;
            padding: 0;
            color: lime;
            font-family: monospace;
            margin-left: 0.5cm;
        }}
        pre {{
            border: none;
            margin: 0;
            padding: 0;
            color: lime;
            white-space: pre;
        }}
        a {{
            color: lime;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        .cursor {{
            display: inline-block;
            animation: blink 1s steps(1) infinite;
        }}
        @keyframes blink {{
            50% {{ opacity: 0; }}
        }}
        .prompt {{
            color:orange
        }}
        .dir {{
            color:white
        }}
    </style>
</head>
<body onload="document.getElementById('theDate').textContent = formatLinuxDate()">
<!-- ::spiralbend:: autogenerated index -->
<script>
function formatLinuxDate(date = new Date()) {{
  const days   = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const d      = date;
  const dayName   = days[d.getDay()];
  const monthName = months[d.getMonth()];
  const day       = String(d.getDate()).padStart(2, ' ');
  const hh        = String(d.getHours()).padStart(2, '0');
  const mm        = String(d.getMinutes()).padStart(2, '0');
  const ss        = String(d.getSeconds()).padStart(2, '0');
  const year      = d.getFullYear();
  const tz = new Intl.DateTimeFormat('en-US',{{ timeZoneName: 'short' }})
               .formatToParts(d)
               .find(part => part.type === 'timeZoneName')
               .value;
  return `${{dayName}} ${{monthName}} ${{day}} ${{hh}}:${{mm}}:${{ss}} ${{tz}} ${{year}}`;
}}
</script>
<pre>

<span class="prompt">𝜟<span class="dir"><span style="letter-spacing:-0.5ch;"> </span>{dir}</span>·</span> ll
total {total_size}
{entries}
<span class="prompt">𝜟<span class="dir"><span style="letter-spacing:-0.5ch;"> </span>{dir}</span>·</span> date<br><span id="theDate"></span>
<span class="prompt">𝜟<span class="dir"><span style="letter-spacing:-0.5ch;"> </span>{dir}</span>·</span> <span class="cursor"><b>_</b></span>
</pre>
</body>
</html>
"""

TOKEN = "::spiralbend:: autogenerated index"


def human_readable_size(size):
    for unit in ["B", "K", "M", "G", "T"]:
        if size < 1024.0:
            return f"{size:>4.1f}{unit}" if unit != "B" else f"{int(size):>4d}{unit}"
        size /= 1024.0
    return f"{size:.1f}P"


def get_mode_str(mode):
    return stat.filemode(mode) + "."


def classify_suffix(st_mode, is_dir, full_path):
    if is_dir:
        return "/"
    elif stat.S_ISLNK(st_mode):
        return "@"
    elif stat.S_ISFIFO(st_mode):
        return "|"
    elif stat.S_ISSOCK(st_mode):
        return "="
    elif os.access(full_path, os.X_OK):
        return "*"
    else:
        return ""


def format_entry(mode, nlink, size, mtime, name, href, is_dir, full_path):
    size_str = human_readable_size(size) if not is_dir else ""
    now = datetime.datetime.now()
    six_months = datetime.timedelta(days=182)
    if mtime < now - six_months or mtime > now + six_months:
        date_str = mtime.strftime("%b %e  %Y")
    else:
        date_str = mtime.strftime("%b %e %H:%M")
    style = get_color_style(os.lstat(full_path).st_mode, full_path)
    style_attr = f' style="{style}"' if style else ""
    link = f'<a href="{href}"{style_attr}>{name}</a>'
    return f"{mode:11} {nlink:>2} {size_str:>6} {date_str} {link}"


def build_index(dirpath, rel_dir, dirnames, filenames, include_dotfiles):
    entries = []
    total_size = 0

    rel_parent = os.path.relpath(os.path.join(dirpath, ".."), dirpath)
    parent_full = os.path.join(dirpath, "..")
    parent_mtime = datetime.datetime.fromtimestamp(os.lstat(parent_full).st_mtime)
    entries.append(
        format_entry(
            get_mode_str(os.lstat(parent_full).st_mode),
            1,
            0,
            parent_mtime,
            "..",
            rel_parent,
            True,
            parent_full,
        )
    )

    all_entries = sorted(dirnames + filenames, key=str.lower)
    all_entries = [n for n in all_entries if n.lower() != "index.html"]
    for name in all_entries:
        if not include_dotfiles and name.startswith((".", "__")):
            continue
        full_path = os.path.join(dirpath, name)
        try:
            st = os.lstat(full_path)
        except FileNotFoundError:
            continue
        is_dir = stat.S_ISDIR(st.st_mode)
        suffix = classify_suffix(st.st_mode, is_dir, full_path)
        display_name = name + suffix

        entries.append(
            format_entry(
                get_mode_str(st.st_mode),
                st.st_nlink,
                st.st_size,
                datetime.datetime.fromtimestamp(st.st_mtime),
                display_name,
                f"{name}/" if is_dir else name,
                is_dir,
                full_path,
            )
        )
        if not is_dir:
            total_size += st.st_size

    return TEMPLATE.format(
        path=rel_dir if rel_dir != "." else "",
        dir=Path(rel_dir).name,
        entries="\n".join(entries),
        total_size=human_readable_size(total_size),
    )


def process_dir(root, include_dotfiles=False, verbose=False, no_depth=False):
    global skipped
    for dirpath, dirnames, filenames in os.walk(root):
        # if --no-depth, only process the root directory
        if no_depth and os.path.abspath(dirpath) != os.path.abspath(root):
            break

        rel_dir = os.path.relpath(dirpath, root)
        if (
            rel_dir != "."
            and not include_dotfiles
            and any(part.startswith((".", "__")) for part in rel_dir.split(os.sep))
        ):
            continue

        index_path = os.path.join(dirpath, "index.html")
        index_exists = os.path.exists(index_path)
        html = build_index(dirpath, rel_dir, dirnames, filenames, include_dotfiles)

        if index_exists:
            try:
                with open(index_path, "r") as fh:
                    content = fh.read()
            except Exception as e:
                if verbose:
                    print(f"Error reading {index_path}: {e}")
                continue

            if TOKEN not in content:
                if verbose:
                    print(f"Skipping existing index (no token): {index_path}")
                continue

            if content.strip() == html.strip():
                skipped += 1
                if verbose:
                    print(f"Skipping unmodified index: {index_path}")
                continue

        with open(index_path, "w") as fh:
            fh.write(html)
            print(f"{'Updated' if index_exists else 'Created'} index: {index_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate terminal-style index.html files for a directory tree."
    )
    parser.add_argument(
        "root", nargs="?", default=".", help="Root directory to start from (default: .)"
    )
    parser.add_argument(
        "--include-dotfiles",
        action="store_true",
        help="Include dotfiles and dot directories",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="Print progress while generating indexes"
    )
    parser.add_argument(
        "--no-depth",
        action="store_true",
        help="Only generate index.html in the root directory, no sub‑dirs",
    )
    args = parser.parse_args()
    process_dir(
        args.root,
        include_dotfiles=args.include_dotfiles,
        verbose=args.verbose,
        no_depth=args.no_depth,
    )
    if not args.verbose:
        print(f"Skipped {skipped} unmodified indexes.")
